name: Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: echo "Deploy Enviroment URL $BASE_URL"
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
